// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authorize.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ReqAuthorize 授权验证请求
type ReqAuthorize struct {
	Userid               int64    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Appcode              string   `protobuf:"bytes,3,opt,name=appcode,proto3" json:"appcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAuthorize) Reset()         { *m = ReqAuthorize{} }
func (m *ReqAuthorize) String() string { return proto.CompactTextString(m) }
func (*ReqAuthorize) ProtoMessage()    {}
func (*ReqAuthorize) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffbc3c71370bee9a, []int{0}
}

func (m *ReqAuthorize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAuthorize.Unmarshal(m, b)
}
func (m *ReqAuthorize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAuthorize.Marshal(b, m, deterministic)
}
func (m *ReqAuthorize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAuthorize.Merge(m, src)
}
func (m *ReqAuthorize) XXX_Size() int {
	return xxx_messageInfo_ReqAuthorize.Size(m)
}
func (m *ReqAuthorize) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAuthorize.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAuthorize proto.InternalMessageInfo

func (m *ReqAuthorize) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *ReqAuthorize) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ReqAuthorize) GetAppcode() string {
	if m != nil {
		return m.Appcode
	}
	return ""
}

// RespAuthorize 授权验证响应
type RespAuthorize struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token                string            `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Session              map[string]string `protobuf:"bytes,4,rep,name=session,proto3" json:"session,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RespAuthorize) Reset()         { *m = RespAuthorize{} }
func (m *RespAuthorize) String() string { return proto.CompactTextString(m) }
func (*RespAuthorize) ProtoMessage()    {}
func (*RespAuthorize) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffbc3c71370bee9a, []int{1}
}

func (m *RespAuthorize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespAuthorize.Unmarshal(m, b)
}
func (m *RespAuthorize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespAuthorize.Marshal(b, m, deterministic)
}
func (m *RespAuthorize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespAuthorize.Merge(m, src)
}
func (m *RespAuthorize) XXX_Size() int {
	return xxx_messageInfo_RespAuthorize.Size(m)
}
func (m *RespAuthorize) XXX_DiscardUnknown() {
	xxx_messageInfo_RespAuthorize.DiscardUnknown(m)
}

var xxx_messageInfo_RespAuthorize proto.InternalMessageInfo

func (m *RespAuthorize) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespAuthorize) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RespAuthorize) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RespAuthorize) GetSession() map[string]string {
	if m != nil {
		return m.Session
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqAuthorize)(nil), "pb.ReqAuthorize")
	proto.RegisterType((*RespAuthorize)(nil), "pb.RespAuthorize")
	proto.RegisterMapType((map[string]string)(nil), "pb.RespAuthorize.SessionEntry")
}

func init() { proto.RegisterFile("authorize.proto", fileDescriptor_ffbc3c71370bee9a) }

var fileDescriptor_ffbc3c71370bee9a = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0x2d, 0xc9,
	0xc8, 0x2f, 0xca, 0xac, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x0a, 0xe1, 0xe2, 0x09, 0x4a, 0x2d, 0x74, 0x84, 0xc9, 0x08, 0x89, 0x71, 0xb1, 0x95, 0x16, 0xa7,
	0x16, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79, 0x42, 0x42, 0x5c, 0x2c,
	0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17,
	0x7b, 0x62, 0x41, 0x01, 0x58, 0x98, 0x19, 0x2c, 0x0c, 0xe3, 0x2a, 0x1d, 0x64, 0xe4, 0xe2, 0x0d,
	0x4a, 0x2d, 0x2e, 0x40, 0x98, 0x0b, 0xd3, 0x0f, 0x32, 0x95, 0x15, 0xaa, 0x5f, 0x80, 0x8b, 0x39,
	0xb7, 0x38, 0x1d, 0x6a, 0x24, 0x88, 0x29, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x9f, 0x9d, 0x9a, 0x07,
	0x35, 0x0f, 0xc2, 0x11, 0xb2, 0xe0, 0x62, 0x2f, 0x4e, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0x93, 0x60,
	0x51, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd3, 0x2b, 0x48, 0xd2, 0x43, 0x31, 0x5f, 0x2f, 0x18, 0xa2,
	0xc0, 0x35, 0xaf, 0xa4, 0xa8, 0x32, 0x08, 0xa6, 0x5c, 0xca, 0x8a, 0x8b, 0x07, 0x59, 0x02, 0x64,
	0x63, 0x76, 0x6a, 0x25, 0xd8, 0x11, 0x9c, 0x41, 0x20, 0x26, 0xc8, 0xc6, 0xb2, 0xc4, 0x9c, 0x52,
	0x98, 0xc7, 0x20, 0x1c, 0x2b, 0x26, 0x0b, 0x46, 0x27, 0xce, 0x28, 0x76, 0x3d, 0x3d, 0x7d, 0x50,
	0x98, 0x25, 0xb1, 0x81, 0xc3, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x49, 0xf5, 0xb6, 0x8c,
	0x42, 0x01, 0x00, 0x00,
}
