// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spropb.proto

package spropb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RspCommon 公共响应数据
type RspCommon struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Ext                  map[string][]byte `protobuf:"bytes,10,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RspCommon) Reset()         { *m = RspCommon{} }
func (m *RspCommon) String() string { return proto.CompactTextString(m) }
func (*RspCommon) ProtoMessage()    {}
func (*RspCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ee4617c902ca3d1, []int{0}
}

func (m *RspCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspCommon.Unmarshal(m, b)
}
func (m *RspCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspCommon.Marshal(b, m, deterministic)
}
func (m *RspCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspCommon.Merge(m, src)
}
func (m *RspCommon) XXX_Size() int {
	return xxx_messageInfo_RspCommon.Size(m)
}
func (m *RspCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_RspCommon.DiscardUnknown(m)
}

var xxx_messageInfo_RspCommon proto.InternalMessageInfo

func (m *RspCommon) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RspCommon) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RspCommon) GetExt() map[string][]byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

func init() {
	proto.RegisterType((*RspCommon)(nil), "spropb.RspCommon")
	proto.RegisterMapType((map[string][]byte)(nil), "spropb.RspCommon.ExtEntry")
}

func init() { proto.RegisterFile("spropb.proto", fileDescriptor_8ee4617c902ca3d1) }

var fileDescriptor_8ee4617c902ca3d1 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0x28, 0xca,
	0x2f, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xa6, 0x33, 0x72,
	0x71, 0x06, 0x15, 0x17, 0x38, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0x09, 0x09, 0x71, 0xb1, 0x24, 0xe7,
	0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0xb9,
	0xc5, 0xe9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x0e, 0x17, 0x73, 0x6a,
	0x45, 0x89, 0x04, 0x97, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x94, 0x1e, 0xd4, 0x5c, 0xb8, 0x29, 0x7a,
	0xae, 0x15, 0x25, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41, 0x20, 0x65, 0x52, 0x66, 0x5c, 0x1c, 0x30,
	0x01, 0x90, 0x59, 0xd9, 0xa9, 0x95, 0x60, 0xe3, 0x39, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6,
	0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0xb0, 0xf9, 0x3c, 0x41, 0x10, 0x8e, 0x15, 0x93, 0x05, 0xa3, 0x13,
	0x77, 0x14, 0xa7, 0x9e, 0x9e, 0x3e, 0xc4, 0xf0, 0x24, 0x36, 0xb0, 0xab, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x57, 0xdd, 0x0c, 0xc5, 0x00, 0x00, 0x00,
}
