// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify.proto

package notify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ReqRegister 客户端请求注册，函数ID：1
type ReqRegister struct {
	User                 map[string]string `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Ext                  map[string][]byte `protobuf:"bytes,10,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReqRegister) Reset()         { *m = ReqRegister{} }
func (m *ReqRegister) String() string { return proto.CompactTextString(m) }
func (*ReqRegister) ProtoMessage()    {}
func (*ReqRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0}
}

func (m *ReqRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegister.Unmarshal(m, b)
}
func (m *ReqRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegister.Marshal(b, m, deterministic)
}
func (m *ReqRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegister.Merge(m, src)
}
func (m *ReqRegister) XXX_Size() int {
	return xxx_messageInfo_ReqRegister.Size(m)
}
func (m *ReqRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegister proto.InternalMessageInfo

func (m *ReqRegister) GetUser() map[string]string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ReqRegister) GetExt() map[string][]byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

// RspRegister 服务端响应注册，函数ID：2
type RspRegister struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Ext                  map[string][]byte `protobuf:"bytes,10,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RspRegister) Reset()         { *m = RspRegister{} }
func (m *RspRegister) String() string { return proto.CompactTextString(m) }
func (*RspRegister) ProtoMessage()    {}
func (*RspRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{1}
}

func (m *RspRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspRegister.Unmarshal(m, b)
}
func (m *RspRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspRegister.Marshal(b, m, deterministic)
}
func (m *RspRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspRegister.Merge(m, src)
}
func (m *RspRegister) XXX_Size() int {
	return xxx_messageInfo_RspRegister.Size(m)
}
func (m *RspRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_RspRegister.DiscardUnknown(m)
}

var xxx_messageInfo_RspRegister proto.InternalMessageInfo

func (m *RspRegister) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RspRegister) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RspRegister) GetExt() map[string][]byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

// PushNotifyMsg 服务端推送通知消息，函数ID：3
type PushNotifyMsg struct {
	Type                 int32             `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	NotifyMsg            []byte            `protobuf:"bytes,2,opt,name=notifyMsg,proto3" json:"notifyMsg,omitempty"`
	Ext                  map[string][]byte `protobuf:"bytes,10,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PushNotifyMsg) Reset()         { *m = PushNotifyMsg{} }
func (m *PushNotifyMsg) String() string { return proto.CompactTextString(m) }
func (*PushNotifyMsg) ProtoMessage()    {}
func (*PushNotifyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{2}
}

func (m *PushNotifyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushNotifyMsg.Unmarshal(m, b)
}
func (m *PushNotifyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushNotifyMsg.Marshal(b, m, deterministic)
}
func (m *PushNotifyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushNotifyMsg.Merge(m, src)
}
func (m *PushNotifyMsg) XXX_Size() int {
	return xxx_messageInfo_PushNotifyMsg.Size(m)
}
func (m *PushNotifyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushNotifyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushNotifyMsg proto.InternalMessageInfo

func (m *PushNotifyMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PushNotifyMsg) GetNotifyMsg() []byte {
	if m != nil {
		return m.NotifyMsg
	}
	return nil
}

func (m *PushNotifyMsg) GetExt() map[string][]byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

// NotifyMsg 业务服务产生通知消息，发送至kafka的t_notify话题，推送服务消费消息并路由至客户端
type NotifyMsg struct {
	UserId               int64             `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AppId                int32             `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Type                 int32             `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	NotifyMsg            []byte            `protobuf:"bytes,4,opt,name=notifyMsg,proto3" json:"notifyMsg,omitempty"`
	Ext                  map[string][]byte `protobuf:"bytes,10,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NotifyMsg) Reset()         { *m = NotifyMsg{} }
func (m *NotifyMsg) String() string { return proto.CompactTextString(m) }
func (*NotifyMsg) ProtoMessage()    {}
func (*NotifyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{3}
}

func (m *NotifyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMsg.Unmarshal(m, b)
}
func (m *NotifyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMsg.Marshal(b, m, deterministic)
}
func (m *NotifyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMsg.Merge(m, src)
}
func (m *NotifyMsg) XXX_Size() int {
	return xxx_messageInfo_NotifyMsg.Size(m)
}
func (m *NotifyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMsg proto.InternalMessageInfo

func (m *NotifyMsg) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *NotifyMsg) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *NotifyMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NotifyMsg) GetNotifyMsg() []byte {
	if m != nil {
		return m.NotifyMsg
	}
	return nil
}

func (m *NotifyMsg) GetExt() map[string][]byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqRegister)(nil), "pb.ReqRegister")
	proto.RegisterMapType((map[string][]byte)(nil), "pb.ReqRegister.ExtEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.ReqRegister.UserEntry")
	proto.RegisterType((*RspRegister)(nil), "pb.RspRegister")
	proto.RegisterMapType((map[string][]byte)(nil), "pb.RspRegister.ExtEntry")
	proto.RegisterType((*PushNotifyMsg)(nil), "pb.PushNotifyMsg")
	proto.RegisterMapType((map[string][]byte)(nil), "pb.PushNotifyMsg.ExtEntry")
	proto.RegisterType((*NotifyMsg)(nil), "pb.NotifyMsg")
	proto.RegisterMapType((map[string][]byte)(nil), "pb.NotifyMsg.ExtEntry")
}

func init() { proto.RegisterFile("notify.proto", fileDescriptor_aba76cc4ebe272d4) }

var fileDescriptor_aba76cc4ebe272d4 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcb, 0x2f, 0xc9,
	0x4c, 0xab, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xba, 0xc9, 0xc8,
	0xc5, 0x1d, 0x94, 0x5a, 0x18, 0x94, 0x9a, 0x9e, 0x59, 0x5c, 0x92, 0x5a, 0x24, 0xa4, 0xcb, 0xc5,
	0x52, 0x5a, 0x9c, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa9, 0x57, 0x90, 0xa4,
	0x87, 0x24, 0xad, 0x17, 0x5a, 0x9c, 0x5a, 0xe4, 0x9a, 0x57, 0x52, 0x54, 0x19, 0x04, 0x56, 0x26,
	0xa4, 0xc5, 0xc5, 0x9c, 0x5a, 0x51, 0x22, 0xc1, 0x05, 0x56, 0x2d, 0x81, 0xae, 0xda, 0xb5, 0xa2,
	0x04, 0xa2, 0x18, 0xa4, 0x48, 0xca, 0x9c, 0x8b, 0x13, 0xae, 0x5d, 0x48, 0x80, 0x8b, 0x39, 0x3b,
	0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x14, 0x12, 0xe1, 0x62, 0x2d, 0x4b,
	0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c, 0x52, 0x66, 0x5c,
	0x1c, 0x30, 0x93, 0x08, 0xe9, 0xe3, 0x41, 0xd2, 0xa7, 0x34, 0x1d, 0xe4, 0xb7, 0xe2, 0x02, 0xb8,
	0xdf, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0xc1, 0x9a, 0x59, 0x83, 0xc0, 0x6c, 0x90, 0x79,
	0xb9, 0xc5, 0xe9, 0x50, 0x3b, 0x41, 0x4c, 0x6c, 0x5e, 0x42, 0x98, 0x81, 0xe6, 0x25, 0x72, 0x5d,
	0xb6, 0x9c, 0x91, 0x8b, 0x37, 0xa0, 0xb4, 0x38, 0xc3, 0x0f, 0x1c, 0x1d, 0xbe, 0xc5, 0xe9, 0x20,
	0xb7, 0x95, 0x54, 0x16, 0xc0, 0xdd, 0x06, 0x62, 0x0b, 0xc9, 0x70, 0x71, 0xe6, 0xc1, 0x14, 0x40,
	0xcd, 0x40, 0x08, 0x08, 0xe9, 0x20, 0xbb, 0x53, 0x0a, 0xe4, 0x4e, 0x14, 0x13, 0xa9, 0xe4, 0xd2,
	0xb3, 0x8c, 0x5c, 0x9c, 0x08, 0x57, 0x8a, 0x71, 0xb1, 0x81, 0xa2, 0xdd, 0x33, 0x05, 0xac, 0x99,
	0x39, 0x08, 0xca, 0x03, 0xe9, 0x4f, 0x2c, 0x28, 0xf0, 0x4c, 0x01, 0xeb, 0x67, 0x0d, 0x82, 0x70,
	0xe0, 0x7e, 0x62, 0xc6, 0xe5, 0x27, 0x16, 0x74, 0x3f, 0x69, 0x20, 0xfb, 0x49, 0x0c, 0xe4, 0x27,
	0x2a, 0xfb, 0xc7, 0x89, 0x3b, 0x8a, 0x53, 0x4f, 0x4f, 0x1f, 0x62, 0x63, 0x12, 0x1b, 0x38, 0x1f,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x60, 0xc8, 0xf1, 0xdb, 0x17, 0x03, 0x00, 0x00,
}
