package constant

/* 资源变化类型常量定义 */
const (
	PropChangeTypeValueInflate               = 121 // 价值膨胀
	PropChangeMayDayPayReward                = 122 // 五一累充领取
	PropChangeTypeWelFareAutoOpen            = 123 // 福利任务自动开宝箱
	PropChangeGoodFortuneReward              = 124 // 鸿运金
	PropTreasureDailyReward                  = 125 // 神秘宝藏日常领取
	PropLuckyRichReward                      = 126 // 幸运大富翁
	PropLuckyRichExtraReward                 = 127 // 幸运大富翁额外奖励领取
	PropGunPieceCompose                      = 128 // 碎片合成
	PropHolidayDailyReward                   = 129 // 节日礼包领取
	PropChangeTypeOnlineInGame               = 130 // 在线捕鱼活动
	PropChangeTypeNewYearJTSFMonster         = 131 // 金兔送福-炸年兽
	PropChangeTypeNewYearJTSFOpenRewards     = 132 // 金兔送福-五福开奖
	PropChangeTypeNewYearJTSFExchange        = 133 // 金兔送福-兑换奖励
	PropChangeTypeNewYearJTYCContinue        = 134 // 金兔迎春-连续奖励
	PropChangeTypeNewYearJTYCSignIn          = 135 // 金兔迎春-签到
	PropChangeTypeChristmasExchangeTree      = 136 // 圣诞节宝箱圣诞树开启
	PropChangeTypeChristmasExchangeNormal    = 137 // 圣诞节宝箱普通奖励
	PropChangeTypeChristmasExchangeBox       = 138 // 圣诞节宝箱奖励
	PropChangeTypeClubSwitchDownScore        = 139 // 切换俱乐部下分
	PropChangeTypeClubSwitchUpScore          = 140 // 切换俱乐部上分
	PropChangeTypeClubDownScore              = 141 // 俱乐部下分
	PropChangeTypeClubUpScore                = 142 // 俱乐部上分
	PropChangeTypeClubAddTimeRoom            = 143 // 俱乐部续约房间
	PropChangeTypeClubUnlockRoom             = 145 // 俱乐部解锁房间
	PropChangeTypeInviteFriend               = 146 // 邀请好友助力奖励
	PropChangeTypeRegressResetChainKnot      = 147 // 回归赐福-清除玩家中国结数量
	PropChangeTypeRegressTaskMul             = 148 // 回归赐福任务-奖励一键领取
	PropChangeTypeRegressTaskOne             = 149 // 回归赐福任务-奖励单领
	PropChangeTypeRegressRewardsMul          = 150 // 回归赐福礼包-奖励一键领取
	PropChangeTypeRegressRewardsOne          = 151 // 回归赐福礼包-奖励单领
	PropChangeTypeRegressPayTask             = 152 // 回归奖励-充值任务奖励
	PropChangeTypeRegressLogin               = 153 // 回归奖励-登陆豪礼
	PropChangeTypeHuaweiComment              = 154 // 华为评分奖励
	PropChangeTypeCompensateVipGun           = 155 // vip等级1的炮台补偿
	PropChangeTypeSignInContinuous           = 156 // 连续签到奖励
	PropChangeTypeRechargePartyRewards       = 157 // 充值派对奖励
	PropChangeTypeSignInSupplementary        = 158 // 签到补签
	PropChangeTypePrivilegeMonth             = 159 // 特权月卡
	PropChangeTypeAutoFire                   = 160 // 自动开炮卡补偿
	PropChangeTypeWishTreeBuyWater           = 161 // 许愿树购买圣水
	PropChangeTypeWishTree                   = 162 // 许愿树奖励
	PropChangeTypePushMsgRewards             = 163 // 推送消息奖励
	PropChangeTypeGoldDepot                  = 164 // 渔币救济站
	PropChangeTypeExpirePropsShare           = 165 // 过期道具赠送
	PropChangeTypeSevenDayIntegral           = 166 // 七日福利任务活跃度奖励
	PropChangeTypeSevenDayTasksComplete      = 167 // 七日福利任务日完成度奖励
	PropChangeTypeSevenDayTaskReward         = 168 // 七日福利任务奖励
	PropChangeTypeNoviceThreeDay             = 169 // 新手三日礼包奖励
	PropChangeTypeWelfareExchangeBox         = 170 // 福利兑换奖励宝箱
	PropChangeTypeWelfareTaskBox             = 171 // 福利兑换任务奖励宝箱
	PropChangeTypeLuckyBallReward            = 172 // 弹珠奖励
	PropChangeTypeLuckyBallExchange          = 173 // 弹珠兑换
	PropChangeTypeWelFareCompensate          = 174 // 福利兑换活动物品回收补偿
	PropChangeTypeWeekMonthGiftBag           = 175 // 周礼包月礼包奖励
	PropChangeTypeWelfareExchange            = 176 // 福利兑换
	PropChangeTypeWelfareReward              = 177 // 福利活动奖励
	PropChangeTypeDailyProgressReward        = 178 // 每日任务进度奖励
	PropChangeTypeDailyTaskReward            = 179 // 每日任务奖励
	PropChangeTypeFishCardReward             = 180 // 猎鱼宝册升级奖励
	PropChangeTypeThirtySignInBox            = 181 // 30日签到奖励开宝箱
	PropChangeTypeThirtySignIn               = 182 // 30日签到奖励
	PropChangeTypeAchievementUpgrade         = 183 // 成就称号升级奖励
	PropChangeTypeAchievementRewards         = 184 // 领取成就奖励
	PropChangeTypeSeniorGrowthRewards        = 185 // 领取荣耀成长基金奖励
	PropChangeTypeDeityShopExchange          = 186 // 商店-神器典藏库积分宝库兑换商品
	PropChangeTypeDeityStoneRewards          = 187 // 商店-神器典藏库领取奖励
	PropChangeTypeShopGoldExCrystal          = 188 // 商店-鱼币换水晶
	PropChangeTypeMailCompensateBase         = 189 // 邮件补偿道具 - 清空基础道具
	PropChangeTypeMailCompensateSenior       = 190 // 邮件补偿道具 - 清空高级道具
	PropChangeTypeShenQiFuse                 = 191 // 神将石合成
	PropChangeTypeSignBox                    = 192 // 七日签到开宝箱
	PropChangeTypeFiveBlessLotteryAddBless   = 193 // 五福临门 - 祈福 添加福字奖励
	PropChangeTypeH5GiveProp                 = 194 // h5-赠送道具
	PropChangeTypeBBGSLottery                = 195 // 活动 - 步步高升抽奖
	PropChangeTypeTreasureLottery            = 196 // 招财进宝 - 抽奖
	PropChangeTypeThreeRewardsBox            = 197 // 3日签到 - 领取奖励开宝箱
	PropChangeTypeThreeRewards               = 198 // 3日签到 - 领取奖励
	PropChangeTypeFiveBlessLottery           = 199 // 五福临门 - 祈福
	PropChangeTypeFiveBlessReset             = 200 // 五福临门 - 重置
	PropChangeTypeActivityShopBuy            = 201 // 活动商店(海底宝库)购买道具
	PropChangeTypeShareSignIn                = 202 // 签到分享得宝箱
	PropChangeTypeSignTurntable              = 203 // 签到转盘版
	PropChangeTypeSyncData                   = 204 // 同步数据的道具变更
	PropChangeTypeSeasonClearProp            = 205 // 新赛季清除手册积分
	PropChangeTypeInvitedGoldPig             = 206 // 邀请砸金猪 2021-07-26
	PropChangeTypeWeekCardSuperBoxRewards    = 207 // 至尊周卡 - 宝箱奖励
	PropChangeTypeWeekCardSuperNormalRewards = 208 // 至尊周卡 - 普通奖励
	PropChangeTypeMonthCardBoxRewards        = 209 // 月卡 - 宝箱奖励
	PropChangeTypeMonthCardNormalRewards     = 210 // 月卡 - 普通奖励
	PropChangeTypeVipBankruptGetRewards      = 211 // vip破产补足奖励
	PropChangeTypeInviteDownloadRewards      = 212 // 活动 - 邀请下载App奖励
	PropChangeTypeArtifactWarehouseExchange  = 213 // 神器宝库 - 普通兑换
	PropChangeTypeArtifactWarehouseRefresh   = 214 // 神器宝库 - 刷新
	PropChangeTypeXiYouSkillLvUp             = 215 // 西游技能升级
	PropChangeTypeMysteryTurnTable           = 216 // 神秘转盘
	PropChangeTypeVipFullLightAndGold        = 217 // vip每日补足光棱和鱼币
	PropChangeTypeGoldToadCardMoney          = 218 // 金蟾卡 - 领取充值金蟾卡
	PropChangeTypeGoldToadCardNormal         = 219 // 金蟾卡 - 领取普通金蟾卡
	PropChangeTypeTreasureFeverLookTreasure  = 220 // 神秘宝藏 - 消耗到具寻宝
	PropChangeTypeLuckRedPacketReceive       = 221 // 幸运红包领取
	PropChangeTypeSubscribeCustomer          = 222 // 订阅客服奖励领取
	PropChangeTypeChessPayOrder              = 223 // 棋牌大厅支付订单
	PropChangeType7DaySignInPlusOpenBox      = 224 // 7天签到豪华礼包开宝箱
	PropChangeTypeGet7DaySignInPlusRewards   = 225 // 7天签到豪华礼包奖励
	PropChangeTypeGetSeasonTaskRewards       = 226 // 领取赛季挑战任务奖励
	PropChangeTypeBuySeasonRewardsLevel      = 227 // 购买赛季补给奖励的等级
	PropChangeTypeSeasonRewards              = 228 // 领取赛季补给奖励
	PropChangeFishCoinTransferChess          = 229 // 鱼币转换为棋牌
	PropChangeChessTransferFishCoin          = 230 // 棋牌转换为鱼币
	PropChangeTypePubAttentionReward         = 231 // 关注公众号奖励
	PropChangeTypeH5DailyWelfare             = 232 // h5每日福利
	PropChangeTypeMailBoxDraw                = 233 // 邮件赠送宝箱奖励
	PropChangeTypeVipSendBoxDraw             = 234 // 领取Vip赠送宝箱
	PropChangeTypeGrowthRewards              = 235 // 领取成长基金奖励
	PropChangeTypeExchangeTicketForBox       = 236 // 点券兑换里的开宝箱
	PropChangeTypeExchangeTicket             = 237 // 点券兑换
	PropChangeTypeBindPhone                  = 238 // 绑定手机号奖励
	PropChangeTypeAuthReward                 = 239 // 授权奖励
	PropChangeTypeArenaDrawReward            = 240 // 竞技场-大奖赛奖励领取
	PropChangeTypeOldPlayerBack              = 241 // 老用户回归
	PropChangeTypeSendDefaultGun             = 242 // 赠送默认炮台
	PropChangeTypeLuckRouletteRewardDouble   = 243 // 幸运转盘奖励双倍
	PropChangeTypeCertRewards                = 245 // 实名认证奖励
	PropChangeTypeRechargeAddition           = 246 // 充值触发玩家捕鱼概率的增加
	PropChangeDiamondDrop                    = 247 // 钻石兑换商品活动
	PropChangeTypeDressExchange              = 248 // 服饰兑换
	PropChangeTypeTimeShopRefresh            = 249 // 时间商店刷新
	PropChangeTypeExchangeTimeShop           = 250 // 时间商店兑换
	PropChangeTypeWeekCardAwardReceive       = 251 // 周卡奖励领取
	PropChangeTypeVipUpgradeGiveReward       = 252 // vip升级赠送
	PropChangeTypeExploreGetGiftBag          = 253 // 神域探宝 - 领取礼包
	PropChangeTypeExploreTreasureHunt        = 254 // 神域探宝 - 寻宝
	PropChangeTypeExploreShopBuy             = 255 // 神域探宝 - 商店兑换
	PropChangeTypeExploreLinShiExchange      = 256 // 神域探宝 - 灵石兑换
	PropChangeTypeXinShouYinDao              = 257 // 新手引导[3.7新手引导打到的钱有加到玩家身上,4.0没有加到玩家身上]
	PropChangeTypeRichGodTurnCard            = 258 // 财神秘宝翻牌`
	PropChangeTypeBuyTreasureFever           = 259 // 神秘宝藏购买
	PropChangeTypeLockAndLookTreasureFever   = 260 // 神秘宝藏锁定&寻宝
	PropChangeTypeLuckRoulette               = 261 // 幸运转盘

	PropChangeTypeBigJackpotOctopus      = 262
	PropChangeTypeBigJackpotHigh         = 263 // 大奖池抽奖至尊场
	PropChangeTypePetUnLock              = 264 // 宠物解锁获得
	PropChangeTypeBuyPetShop             = 265 // 宠物商店
	PropChangeTypeBigJackpot             = 266 // 大奖池抽奖千倍房
	PropChangeTypeOtherExchange          = 267 // 兑换其他消耗
	PropChangeTypeAsgardTreasureExchange = 268 // 神域探宝兑换
	PropChangeTypePetCost                = 269 // 宠物消耗
	PropChangeTypeBackReward             = 270 // 老玩家回归奖励
	PropChangeTypeSummerFestival         = 271 // 夏日狂欢
	PropChangeTypeExchangeCode           = 272 // 兑换码
	PropChangeTypeAsgardTreasure         = 273 // 神域探宝
	PropChangeTypeDragonBoatDrop         = 274 // 龙舟节获得
	PropChangeTypeDragonBoatCost         = 275 // 龙舟节消耗
	PropChangeTypeDailyGift              = 276 // 每日签到(818特供)
	PropChangeTypeRedPacket              = 277 // 帮拆红包的
	PropChangeTypeChildren               = 278 // 儿童节
	PropChangeTypeVipCostom              = 280 // vip专属客服奖励
	PropChangeTypeRedEnvelope            = 281 // 邀请红包领奖
	PropChangeTypeGiftTaskShare          = 282 // 新人红包分享
	PropChangeTypeForgeMustCost          = 283 // 锻造必成功水晶消耗
	PropChangeTypeLifeMonthCardAward     = 284 // 终身月卡奖励
	PropChangeTypeDesktop                = 285 // 桌面奖励
	PropChangeTypeInviteGift             = 286 // 邀请豪礼
	PropChangeTypeCrystalBullet          = 287 // 水晶兑换打怪兽炮弹
	PropChangeTypeCrystalCallStone       = 288 // 水晶兑换召唤石
	PropChangeTypePlantTreeReward        = 289 // 植树节领奖励
	PropChangeTypePlantTreeWater         = 290 // 植树节浇水
	PropChangeTypePuzzleFinish           = 291 // 拼图完成奖励
	PropChangeTypePartsCoinExchange      = 292 // 零件币兑换
	PropChangeTypeGunDisassemble         = 293 // 炮台拆解
	PropChangeTypeMedalShopBuy           = 294 // 勋章商店购买
	PropChangeTypeGunShopBuy             = 295 // 炮台商店购买
	PropChangeTypeSilverBox              = 296 // 银宝箱抽奖
	PropChangeTypeHolidayWishTree        = 297 // 许愿树 || 辞旧迎新
	PropChangeTypeNewYearLogin           = 298 // 春节登录
	PropChangeTypeHolidayTurntable       = 299 // 节日转盘
	PropChangeTypeKillFish               = 300 // 杀鱼
	PropChangeTypeSendBullet             = 301 // 发射子弹
	PropChangeTypeUpgradeCannonDrop      = 302 // 升级炮倍奖励
	PropChangeTypeGameDraw               = 303 // 游戏内抽奖
	PropChangeTypeLoginDraw              = 304 // 登陆抽奖
	PropChangeTypeVipDraw                = 305 // vip抽奖
	PropChangeTypeMonthCard              = 306 // 月卡
	PropChangeTypeSignIn                 = 307 // 签到
	PropChangeTypeInitial                = 308 // 启航礼包
	PropChangeTypeAlm                    = 309 // 救济金
	PropChangeTypeReturn                 = 310 // 击中的鱼被其他人打死，返还鱼币
	PropChangeTypeSecret                 = 311 // 秘籍
	PropChangeTypeBuyWithCrystal         = 312 // 用水晶购买获得
	PropChangeTypeBuyCost                = 313 // 鱼券兑换虚拟物品
	PropChangeTypeKillFishDrop           = 314 // 杀鱼掉落
	PropChangeTypeUseProp                = 315 // 使用道具
	PropChangeTypeUseCrystal             = 316 // 使用用水晶
	PropChangeTypeForgeCost              = 317 // 锻造消耗
	PropChangeTypeForgeDrop              = 318 // 锻造掉落
	PropChangeTypeInvite                 = 319 // 邀请有礼
	PropChangeTypeShare                  = 320 // 分享
	PropChangeTypeTimeHourGlass          = 321 // 时光沙漏
	PropChangeTypeUpgradeCannonCost      = 322 // 升级炮倍消耗
	PropChangeTypeDecomposeCost          = 323 // 锻造材料分解消耗
	PropChangeTypeDecomposeDrop          = 324 // 锻造材料分解获得
	PropChangeTypeTaskReward             = 325 // 任务奖励
	PropChangeTypeActiveReward           = 326 // 活跃奖励
	PropChangeTypeVipDailyReward         = 327 // vip每日总送
	PropChangeTypeVipFishIconRecruit     = 328 // vip鱼币补足
	PropChangeTypeFreezeWithCrystal      = 329 // 用水晶冰冻
	PropChangeTypeAimWithCrystal         = 330 // 用水晶瞄准
	PropChangeTypeNBombWithCrystal       = 331 // 用水晶核弹
	PropChangeTypeNBombWithCallFish      = 332 // 用水晶召唤鱼
	PropChangeTypeMail                   = 333 // 邮件
	PropChangeTypeRecievePhoneFare       = 334 // 话费兑换消耗
	PropChangeTypeRecievePhoneFareReturn = 335 // 花费兑换失败返还
	PropChangeTypeUpgrade                = 336 // 升级
	PropChangeTypeViolentWithCrystal     = 337 // 使用钻石狂暴
	PropChangeTypeCannonWithCrystal      = 338 //
	PropChangeTypeCannonWithFishIcon     = 339 //
	PropChangeTypeNewTaskReward          = 340 // 新手任务奖励
	PropChangeTypeSell                   = 341 // 道具出售
	PropChangeTypeSellDrop               = 342 // 道具出售获得
	PropChangeTypeNewerReward            = 343 // 新手奖励
	PropChangeTypeCharge                 = 344 // 充值
	PropChangeTypeFishTicketDrawCost     = 345 // 鱼券抽奖(含获得)
	PropChangeTypeFishTicketDrawGet      = 346 // 鱼券抽奖获得
	PropChangeTypeRedPackage             = 347 // 红包领取
	PropChangeTypeRewardTask             = 348 // 悬赏任务获得
	PropChangeCommonShare                = 349 // 通用分享
	PropChangeMasterSignup               = 350 // 大师赛报名
	PropChangePayFreetime                = 352 // 免费场缴费
	PropChangeTypeFreeFishIcon           = 353 // 免费渔币
	PropChangeTypeBonusPool              = 354 // 奖金池奖励
	PropChangeTypeBossReward             = 355 // 专属boss额外奖励
	PropChangeSeperateGunForge           = 356 // 分身炮台锻造
	PropChangeTomorrowGift               = 357 // 明日礼包
	PropChangeSupermaketFishTicket       = 358 // 商城鱼券兑换
	PropChangeHappyThirtySec             = 359 // 开心30秒
	PropChangeTypeOnlineReward           = 360 // 在线时长奖励
	PropChangeMonster                    = 361 // 打怪兽
	PropChangeTypeShopBuyCost            = 362 // 商城购买
	PropChangeTypeShopBuyGet             = 363 // 商城购买获得
	PropChangeTypeShopBuyFirstCharge     = 364 // 商城首充
	PropChangeTypeShopBuyGif             = 365 // 商城购买礼包
	PropChangeTypeBatchBullet            = 366 // 批量发射子弹
	PropChangeTypeMagicCrystalExchange   = 367 // 魔晶兑换
	PropChangeTypeMagicPearlExchange     = 368 // 魔法宝珠兑换
	PropChangeTypeTimerClean             = 369 // 定时清空
	PropChangeTypeMermaidReward          = 370 // 金蛋奖励
	PropChangeTypeNewGiftReward          = 371 // 新人红包任务奖励
	PropChangeTypeBoomBlast              = 372 // 使用炸弹道具
	PropChangeTypeDrill                  = 373 // 使用钻头
	PropChangeTypePartBoom               = 374 // 局部炸弹
	PropChangeTypeSameBoom               = 375 // 同类炸弹
	PropChangeTypeThunder                = 376 // 闪电鱼
	PropChagneTypeGetVipGift             = 377 // 领取vip礼包获得
	PropChangeTypeBombParadise           = 378 // 炸弹乐园（兑换）
	PropChangeTypeGhostInto              = 379 // 炮弹乐园首次进入
	PropChangeActivity                   = 380 // 活动奖励 充值活动
	PropChangeTypeFund                   = 381 // 捕鱼基金
	PorpChangeTypeSynthetizeItem         = 382 // 合成物品
	PropChangeTypeCrystalDraw            = 383 // 大转盘抽奖
	PropChangeSupermaketFishTicketBack   = 384 // 商城鱼券兑换返还
	PropChangeDiamondCost                = 385 // 钻石兑换商品消耗

	PropChangeTypeGodPigBuy         = 426 // 金猪购买
	PropChangeTypeGodPigLevelReward = 427 // 金猪送福
)
