package http

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *HTTPRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "RemoteAddr":
			z.RemoteAddr, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "RemoteAddr")
				return
			}
		case "Raw":
			z.Raw, err = dc.ReadBytes(z.Raw)
			if err != nil {
				err = msgp.WrapError(err, "Raw")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *HTTPRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "RemoteAddr"
	err = en.Append(0x82, 0xaa, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.RemoteAddr)
	if err != nil {
		err = msgp.WrapError(err, "RemoteAddr")
		return
	}
	// write "Raw"
	err = en.Append(0xa3, 0x52, 0x61, 0x77)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Raw)
	if err != nil {
		err = msgp.WrapError(err, "Raw")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *HTTPRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "RemoteAddr"
	o = append(o, 0x82, 0xaa, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72)
	o = msgp.AppendString(o, z.RemoteAddr)
	// string "Raw"
	o = append(o, 0xa3, 0x52, 0x61, 0x77)
	o = msgp.AppendBytes(o, z.Raw)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *HTTPRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "RemoteAddr":
			z.RemoteAddr, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RemoteAddr")
				return
			}
		case "Raw":
			z.Raw, bts, err = msgp.ReadBytesBytes(bts, z.Raw)
			if err != nil {
				err = msgp.WrapError(err, "Raw")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *HTTPRequest) Msgsize() (s int) {
	s = 1 + 11 + msgp.StringPrefixSize + len(z.RemoteAddr) + 4 + msgp.BytesPrefixSize + len(z.Raw)
	return
}
